# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: decd7a82b12768613dbf8abc287a77ff79f244df7be5330102f888aaefd548898b4c51fad37d6d58cc68accc30e75e1eee324401953b9182cf50f3ecb3d29f03

test:
  secret_key_base: 70369d67641b4cd0a09eb321381e04f1ae971a80a8ac3fbdd0076a6ce31e087322fcee3f38d303268ea8425ab4415d4382a2e91d727b72b9ec9fec4f65696484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
